//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URCP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailTemplateCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplateCode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("URCP.Resources.EmailTemplateCode", typeof(EmailTemplateCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mcico00001.
        /// </summary>
        public static string AcknowledgeEmailForDependingAgence {
            get {
                return ResourceManager.GetString("AcknowledgeEmailForDependingAgence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لديك طلب في انتظار التأشير.
        /// </summary>
        public static string AgencyEmailSubject {
            get {
                return ResourceManager.GetString("AgencyEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mcico00002.
        /// </summary>
        public static string CreateMortgageBankAccountEmailToAgency {
            get {
                return ResourceManager.GetString("CreateMortgageBankAccountEmailToAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mcico00003.
        /// </summary>
        public static string CreateMortgageBankDepositEmailToAgency {
            get {
                return ResourceManager.GetString("CreateMortgageBankDepositEmailToAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mcico00005.
        /// </summary>
        public static string CreateMortgageOtherMoneyTypeEmailToAgency {
            get {
                return ResourceManager.GetString("CreateMortgageOtherMoneyTypeEmailToAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mcico00004.
        /// </summary>
        public static string CreateMortgageSharesEmailToAgency {
            get {
                return ResourceManager.GetString("CreateMortgageSharesEmailToAgency", resourceCulture);
            }
        }
    }
}
