//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URCP.ServicesRepository.NotificationGateway {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendSMSNotificationRequest", Namespace="http://schemas.datacontract.org/2004/07/NotificationsGateway")]
    [System.SerializableAttribute()]
    public partial class SendSMSNotificationRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsArabicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RefrenceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> TemplateValuesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsArabic {
            get {
                return this.IsArabicField;
            }
            set {
                if ((this.IsArabicField.Equals(value) != true)) {
                    this.IsArabicField = value;
                    this.RaisePropertyChanged("IsArabic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNo {
            get {
                return this.MobileNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNoField, value) != true)) {
                    this.MobileNoField = value;
                    this.RaisePropertyChanged("MobileNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefrenceId {
            get {
                return this.RefrenceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RefrenceIdField, value) != true)) {
                    this.RefrenceIdField = value;
                    this.RaisePropertyChanged("RefrenceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateCode {
            get {
                return this.TemplateCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateCodeField, value) != true)) {
                    this.TemplateCodeField = value;
                    this.RaisePropertyChanged("TemplateCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> TemplateValues {
            get {
                return this.TemplateValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateValuesField, value) != true)) {
                    this.TemplateValuesField = value;
                    this.RaisePropertyChanged("TemplateValues");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationResponse", Namespace="http://schemas.datacontract.org/2004/07/NotificationsGateway")]
    [System.SerializableAttribute()]
    public partial class NotificationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((this.RequestIdField.Equals(value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EAICustomError", Namespace="http://schemas.datacontract.org/2004/07/NotificationsGateway")]
    [System.SerializableAttribute()]
    public partial class EAICustomError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusinessMessageArField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusinessMessageEnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessMessageAr {
            get {
                return this.BusinessMessageArField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessMessageArField, value) != true)) {
                    this.BusinessMessageArField = value;
                    this.RaisePropertyChanged("BusinessMessageAr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessMessageEn {
            get {
                return this.BusinessMessageEnField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessMessageEnField, value) != true)) {
                    this.BusinessMessageEnField = value;
                    this.RaisePropertyChanged("BusinessMessageEn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendEmailRequest", Namespace="http://schemas.datacontract.org/2004/07/NotificationsGateway")]
    [System.SerializableAttribute()]
    public partial class SendEmailRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<URCP.ServicesRepository.NotificationGateway.EmailAttachment> EmailAttachmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> EmailBCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> EmailCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> EmailToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsArabicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RefrenceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> TablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> TemplateValuesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<URCP.ServicesRepository.NotificationGateway.EmailAttachment> EmailAttachments {
            get {
                return this.EmailAttachmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAttachmentsField, value) != true)) {
                    this.EmailAttachmentsField = value;
                    this.RaisePropertyChanged("EmailAttachments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> EmailBCC {
            get {
                return this.EmailBCCField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailBCCField, value) != true)) {
                    this.EmailBCCField = value;
                    this.RaisePropertyChanged("EmailBCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> EmailCC {
            get {
                return this.EmailCCField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailCCField, value) != true)) {
                    this.EmailCCField = value;
                    this.RaisePropertyChanged("EmailCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> EmailTo {
            get {
                return this.EmailToField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailToField, value) != true)) {
                    this.EmailToField = value;
                    this.RaisePropertyChanged("EmailTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsArabic {
            get {
                return this.IsArabicField;
            }
            set {
                if ((this.IsArabicField.Equals(value) != true)) {
                    this.IsArabicField = value;
                    this.RaisePropertyChanged("IsArabic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefrenceId {
            get {
                return this.RefrenceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RefrenceIdField, value) != true)) {
                    this.RefrenceIdField = value;
                    this.RaisePropertyChanged("RefrenceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Tables {
            get {
                return this.TablesField;
            }
            set {
                if ((object.ReferenceEquals(this.TablesField, value) != true)) {
                    this.TablesField = value;
                    this.RaisePropertyChanged("Tables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateCode {
            get {
                return this.TemplateCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateCodeField, value) != true)) {
                    this.TemplateCodeField = value;
                    this.RaisePropertyChanged("TemplateCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> TemplateValues {
            get {
                return this.TemplateValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateValuesField, value) != true)) {
                    this.TemplateValuesField = value;
                    this.RaisePropertyChanged("TemplateValues");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailAttachment", Namespace="http://schemas.datacontract.org/2004/07/NotificationsGateway")]
    [System.SerializableAttribute()]
    public partial class EmailAttachment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileData {
            get {
                return this.FileDataField;
            }
            set {
                if ((object.ReferenceEquals(this.FileDataField, value) != true)) {
                    this.FileDataField = value;
                    this.RaisePropertyChanged("FileData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendOTPRequest", Namespace="http://schemas.datacontract.org/2004/07/NotificationsGateway")]
    [System.SerializableAttribute()]
    public partial class SendOTPRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsArabicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsArabic {
            get {
                return this.IsArabicField;
            }
            set {
                if ((this.IsArabicField.Equals(value) != true)) {
                    this.IsArabicField = value;
                    this.RaisePropertyChanged("IsArabic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNo {
            get {
                return this.MobileNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNoField, value) != true)) {
                    this.MobileNoField = value;
                    this.RaisePropertyChanged("MobileNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerifyOTPRequest", Namespace="http://schemas.datacontract.org/2004/07/NotificationsGateway")]
    [System.SerializableAttribute()]
    public partial class VerifyOTPRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNo {
            get {
                return this.MobileNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNoField, value) != true)) {
                    this.MobileNoField = value;
                    this.RaisePropertyChanged("MobileNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerifyOTPResponse", Namespace="http://schemas.datacontract.org/2004/07/NotificationsGateway")]
    [System.SerializableAttribute()]
    public partial class VerifyOTPResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsValidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValid {
            get {
                return this.IsValidField;
            }
            set {
                if ((this.IsValidField.Equals(value) != true)) {
                    this.IsValidField = value;
                    this.RaisePropertyChanged("IsValid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NotificationGateway.INotificationGateway")]
    public interface INotificationGateway {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationGateway/SendSMS", ReplyAction="http://tempuri.org/INotificationGateway/SendSMSResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(URCP.ServicesRepository.NotificationGateway.EAICustomError), Action="http://tempuri.org/INotificationGateway/SendSMSEAICustomErrorFault", Name="EAICustomError", Namespace="http://schemas.datacontract.org/2004/07/NotificationsGateway")]
        URCP.ServicesRepository.NotificationGateway.NotificationResponse SendSMS(URCP.ServicesRepository.NotificationGateway.SendSMSNotificationRequest SendSMSNotificationRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationGateway/SendSMS", ReplyAction="http://tempuri.org/INotificationGateway/SendSMSResponse")]
        System.Threading.Tasks.Task<URCP.ServicesRepository.NotificationGateway.NotificationResponse> SendSMSAsync(URCP.ServicesRepository.NotificationGateway.SendSMSNotificationRequest SendSMSNotificationRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationGateway/SendEmail", ReplyAction="http://tempuri.org/INotificationGateway/SendEmailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(URCP.ServicesRepository.NotificationGateway.EAICustomError), Action="http://tempuri.org/INotificationGateway/SendEmailEAICustomErrorFault", Name="EAICustomError", Namespace="http://schemas.datacontract.org/2004/07/NotificationsGateway")]
        URCP.ServicesRepository.NotificationGateway.NotificationResponse SendEmail(URCP.ServicesRepository.NotificationGateway.SendEmailRequest SendEmailRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationGateway/SendEmail", ReplyAction="http://tempuri.org/INotificationGateway/SendEmailResponse")]
        System.Threading.Tasks.Task<URCP.ServicesRepository.NotificationGateway.NotificationResponse> SendEmailAsync(URCP.ServicesRepository.NotificationGateway.SendEmailRequest SendEmailRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationGateway/SendRestSMS", ReplyAction="http://tempuri.org/INotificationGateway/SendRestSMSResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(URCP.ServicesRepository.NotificationGateway.EAICustomError), Action="http://tempuri.org/INotificationGateway/SendRestSMSEAICustomErrorFault", Name="EAICustomError", Namespace="http://schemas.datacontract.org/2004/07/NotificationsGateway")]
        URCP.ServicesRepository.NotificationGateway.NotificationResponse SendRestSMS(string SendRestSMSRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationGateway/SendRestSMS", ReplyAction="http://tempuri.org/INotificationGateway/SendRestSMSResponse")]
        System.Threading.Tasks.Task<URCP.ServicesRepository.NotificationGateway.NotificationResponse> SendRestSMSAsync(string SendRestSMSRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationGateway/SendOTP", ReplyAction="http://tempuri.org/INotificationGateway/SendOTPResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(URCP.ServicesRepository.NotificationGateway.EAICustomError), Action="http://tempuri.org/INotificationGateway/SendOTPEAICustomErrorFault", Name="EAICustomError", Namespace="http://schemas.datacontract.org/2004/07/NotificationsGateway")]
        URCP.ServicesRepository.NotificationGateway.NotificationResponse SendOTP(URCP.ServicesRepository.NotificationGateway.SendOTPRequest sendOTPRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationGateway/SendOTP", ReplyAction="http://tempuri.org/INotificationGateway/SendOTPResponse")]
        System.Threading.Tasks.Task<URCP.ServicesRepository.NotificationGateway.NotificationResponse> SendOTPAsync(URCP.ServicesRepository.NotificationGateway.SendOTPRequest sendOTPRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationGateway/VerifyOTP", ReplyAction="http://tempuri.org/INotificationGateway/VerifyOTPResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(URCP.ServicesRepository.NotificationGateway.EAICustomError), Action="http://tempuri.org/INotificationGateway/VerifyOTPEAICustomErrorFault", Name="EAICustomError", Namespace="http://schemas.datacontract.org/2004/07/NotificationsGateway")]
        URCP.ServicesRepository.NotificationGateway.VerifyOTPResponse VerifyOTP(URCP.ServicesRepository.NotificationGateway.VerifyOTPRequest verifyOTPRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationGateway/VerifyOTP", ReplyAction="http://tempuri.org/INotificationGateway/VerifyOTPResponse")]
        System.Threading.Tasks.Task<URCP.ServicesRepository.NotificationGateway.VerifyOTPResponse> VerifyOTPAsync(URCP.ServicesRepository.NotificationGateway.VerifyOTPRequest verifyOTPRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotificationGatewayChannel : URCP.ServicesRepository.NotificationGateway.INotificationGateway, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotificationGatewayClient : System.ServiceModel.ClientBase<URCP.ServicesRepository.NotificationGateway.INotificationGateway>, URCP.ServicesRepository.NotificationGateway.INotificationGateway {
        
        public NotificationGatewayClient() {
        }
        
        public NotificationGatewayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotificationGatewayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificationGatewayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificationGatewayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public URCP.ServicesRepository.NotificationGateway.NotificationResponse SendSMS(URCP.ServicesRepository.NotificationGateway.SendSMSNotificationRequest SendSMSNotificationRequest) {
            return base.Channel.SendSMS(SendSMSNotificationRequest);
        }
        
        public System.Threading.Tasks.Task<URCP.ServicesRepository.NotificationGateway.NotificationResponse> SendSMSAsync(URCP.ServicesRepository.NotificationGateway.SendSMSNotificationRequest SendSMSNotificationRequest) {
            return base.Channel.SendSMSAsync(SendSMSNotificationRequest);
        }
        
        public URCP.ServicesRepository.NotificationGateway.NotificationResponse SendEmail(URCP.ServicesRepository.NotificationGateway.SendEmailRequest SendEmailRequest) {
            return base.Channel.SendEmail(SendEmailRequest);
        }
        
        public System.Threading.Tasks.Task<URCP.ServicesRepository.NotificationGateway.NotificationResponse> SendEmailAsync(URCP.ServicesRepository.NotificationGateway.SendEmailRequest SendEmailRequest) {
            return base.Channel.SendEmailAsync(SendEmailRequest);
        }
        
        public URCP.ServicesRepository.NotificationGateway.NotificationResponse SendRestSMS(string SendRestSMSRequest) {
            return base.Channel.SendRestSMS(SendRestSMSRequest);
        }
        
        public System.Threading.Tasks.Task<URCP.ServicesRepository.NotificationGateway.NotificationResponse> SendRestSMSAsync(string SendRestSMSRequest) {
            return base.Channel.SendRestSMSAsync(SendRestSMSRequest);
        }
        
        public URCP.ServicesRepository.NotificationGateway.NotificationResponse SendOTP(URCP.ServicesRepository.NotificationGateway.SendOTPRequest sendOTPRequest) {
            return base.Channel.SendOTP(sendOTPRequest);
        }
        
        public System.Threading.Tasks.Task<URCP.ServicesRepository.NotificationGateway.NotificationResponse> SendOTPAsync(URCP.ServicesRepository.NotificationGateway.SendOTPRequest sendOTPRequest) {
            return base.Channel.SendOTPAsync(sendOTPRequest);
        }
        
        public URCP.ServicesRepository.NotificationGateway.VerifyOTPResponse VerifyOTP(URCP.ServicesRepository.NotificationGateway.VerifyOTPRequest verifyOTPRequest) {
            return base.Channel.VerifyOTP(verifyOTPRequest);
        }
        
        public System.Threading.Tasks.Task<URCP.ServicesRepository.NotificationGateway.VerifyOTPResponse> VerifyOTPAsync(URCP.ServicesRepository.NotificationGateway.VerifyOTPRequest verifyOTPRequest) {
            return base.Channel.VerifyOTPAsync(verifyOTPRequest);
        }
    }
}
